### ISSUE TITLE
Add supports to bridge

### ISSUE THREAD

**Issue by kreichwe** [RinglingGameArt/2014-Racing-Game#134]
Purely an aesthetic thing. The bridge in your level looks unnatural without supports. Maybe add an arch of wooden trusses?
![capture](https://f.cloud.github.com/assets/7010889/2499429/4db0656c-b356-11e3-8bf9-67069970ab84.JPG)

**Comment by esmith24601** [comment]
Added set dressing supports, it looks much better now.
