### ISSUE TITLE
Car got caught on something 

### ISSUE THREAD

**Issue by AJSHanson** [RinglingGameArt/2014-Racing-Game#135]
Soon after the banked turn there is a spot that can "grab" the player- the car got stuck on it. Might have just been a little glitch, but there may be something that can be fixed.  
![esmith](https://f.cloud.github.com/assets/3964555/2499446/8ca4afbc-b356-11e3-815a-270656c45885.jpg)

**Comment by esmith24601** [comment]
Collision on those rocks has been taken off, so you won't get caught there anymore.
