### ISSUE TITLE
Ramp Speed Boost Combo Needs Fixing!

### ISSUE THREAD

**Issue by srussel1** [RinglingGameArt/2014-Racing-Game#138]
The ramp you take outside in the airplane junk yard that leads through a speed boost literally takes the car and throws it upside-down to the fence and perhaps over the edge.
![bugfixsquinn1](https://f.cloud.github.com/assets/7010874/2499483/33822b98-b357-11e3-84eb-8e44ee52a762.jpg)

**Comment by squinnspazdaxx** [comment]
I dropped the power of the boosts to a noticeable but not throw-able level.
