### ISSUE TITLE
Speed Boosts Too Powerful

### ISSUE THREAD

**Issue by srussel1** [RinglingGameArt/2014-Racing-Game#145]
The Power of the speed boosts provides no turning power at all. Tends to flip the car.
![bugfixsquinn2](https://f.cloud.github.com/assets/7010874/2499530/ba6e1752-b357-11e3-9a56-9867223aed8a.jpg)

**Comment by squinnspazdaxx** [comment]
Dropped the boost power from 3000 to 2000. Boost still apparent, but doesn't throw you.
