### ISSUE TITLE
Stuck

### ISSUE THREAD

**Issue by bakedpudding** [RinglingGameArt/2014-Racing-Game#159]
If you go over the ramp too slow, and get stuck on ground floor in between both ramps. you will get stuck and have to drive around until hitting a reset player zone.
Ramp where the player can fall and get stuck.
![untitled-1](https://f.cloud.github.com/assets/7010877/2499610/c05d825a-b358-11e3-8d87-e1d431d55e56.jpg)

**Comment by esmith24601** [comment]
The Max trigger count was set to 1 instead of 0, it should work now!
