### ISSUE TITLE
Cave Not Cave-like

### ISSUE THREAD

**Issue by egingric** [RinglingGameArt/2014-Racing-Game#160]
Your cave does not look like a cave. It looks like I am driving through a giant coconut instead. Make it darker, change the textures. Ceiling is too high, entrance / exit does not look like a shape that rocks could make.
![cavehuh](https://f.cloud.github.com/assets/3945065/2499637/0913e8fe-b359-11e3-82cb-a67b286c7237.jpg)

**Comment by zforrest** [comment]
Fixed.
