### ISSUE TITLE
Odd Clipping Issue

### ISSUE THREAD

**Issue by srussel1** [RinglingGameArt/2014-Racing-Game#174]
I noticed that at the start you can see a tree clipping through the ground to the right. Even if you drive straight, you sort of see it being clipped though.
![bugfixzforrest5](https://f.cloud.github.com/assets/7010874/2499810/50089e60-b35b-11e3-8dd6-57038bbb3710.jpg)

**Comment by zforrest** [comment]
Moved tree to not clip.
