### ISSUE TITLE
Can Get Above the Level!

### ISSUE THREAD

**Issue by srussel1** [RinglingGameArt/2014-Racing-Game#175]
I was able to get above the level itself upon boosting up the wall with boost pads on it past the first set of propeller obstacles.
![bugfixsquinn3](https://f.cloud.github.com/assets/7010874/2499875/4a1bca94-b35c-11e3-9d49-5a1d2e3544aa.jpg)

**Comment by squinnspazdaxx** [comment]
Try getting up there now! Mwahahahahahahahahaha!
