### ISSUE TITLE
Opening in the Map

### ISSUE THREAD

**Issue by srussel1** [RinglingGameArt/2014-Racing-Game#177]
I tried to leave the map by making an immediate right instead of the left near the first set of propeller obstacles and was capable of leaving the map.
![bugfixsquinn4](https://f.cloud.github.com/assets/7010874/2499937/08ee28a4-b35d-11e3-8654-ede57c2033ce.jpg)
![bugfixsquinn4 1](https://f.cloud.github.com/assets/7010874/2499938/0d47c5cc-b35d-11e3-8b97-3eb3abc9c7bf.jpg)

**Comment by squinnspazdaxx** [comment]
lol, I feel like the line guy at Disneyland! That part's been closed off now!
