### ISSUE TITLE
[FIXED] Fruit does not wake on level start

### ISSUE THREAD

**Issue by zforrest** [RinglingGameArt/2014-Racing-Game#2]
[FIXED] Fruit floats in the air.

**Comment by egingric** [comment]
Whenever you close a bug make sure you mark it with the appropriate label, like "fixed." Or put a comment in.

**Comment by zforrest** [comment]
Sorry! I'll make sure I do that next time.

**Comment by egingric** [comment]
Or right now, to that bug, please. You can continue to edit it after it is
closed.

Regards,
-Eric

**Comment by zforrest** [comment]
All fixed. Didn't know we could edit it again.

**Comment by egingric** [comment]
Thanks! Weird, I didn't know responding to your email also made a comment on this bug!
