### ISSUE TITLE
No collision.

### ISSUE THREAD

**Issue by rhuberga** [RinglingGameArt/2014-Racing-Game#20]
Not quite sure what happened but I fell through the ground right after the waterfall/ chess set.

**Comment by scarroll** [comment]
Someone added me to this github list but I don’t know who any of you are and I don’t play this game.

Please remove my email address.

Law Offices of Susan Carroll, PLLC
6041 California Ave. SW, Suite 101
Seattle, WA  98136
Tele: 206-452-5483
Fax:  206-452-5688
sc@susancarrolllaw.com
www.susancarrolllaw.com

This e-mail is confidential and intended only for the use of the individual to whom it is addressed, and may contain attorney/client privileged information.  If you receive this communication in error, please return this e-mail to the sender and delete it from your files.  Thank you.

**Comment by srussel1** [comment]
Took a look at it and fixed the issue.
