### ISSUE TITLE
Can't see unique landmark while racing

### ISSUE THREAD

**Issue by egingric** [RinglingGameArt/2014-Racing-Game#210]
Adjust road angle so that we can see your tiki as we approach.
![cantsee](https://f.cloud.github.com/assets/3945065/2500154/9292330a-b35f-11e3-8f73-cdbe38af98ba.jpg)

**Comment by mvolpa1** [comment]
I angled it upwards as high as I could before it messed up with the speed of the car.

![hero asset](https://cloud.githubusercontent.com/assets/7010880/2563115/0f7c432a-b873-11e3-90fb-2a46350c102c.jpg)
