### ISSUE TITLE
Bridge Needs A Safety Net!

### ISSUE THREAD

**Issue by srussel1** [RinglingGameArt/2014-Racing-Game#214]
The railings cut out (Intentional, I'm sure), yet there's no catches for the player if they try to drive off. Rather, I'm put onto the second half of the track and can't escape it.

![bugfixmvolpa5](https://f.cloud.github.com/assets/7010874/2500156/a16b7fda-b35f-11e3-88e6-303392a81e67.jpg)

**Comment by mvolpa1** [comment]
Fixed.
