### ISSUE TITLE
Megan - Soft Underbelly Exposed

### ISSUE THREAD

**Issue by esmith2** [RinglingGameArt/2014-Racing-Game#216]
@mrose80 One of your spikes flipped my Jimmy, and I couldn't flip it back. Maybe check your physical material?

![screenshot00002](https://f.cloud.github.com/assets/7010873/2500181/039ef51a-b360-11e3-9bde-31848b2bf2cc.png)

**Comment by bakedpudding** [comment]
i tweaked the spikes, and i can't get this to happen anymore
hope that helped
