### ISSUE TITLE
Ramp Needs Fence

### ISSUE THREAD

**Issue by srussel1** [RinglingGameArt/2014-Racing-Game#234]
The speed boost ramp could use a fence or guard rail. Missing the tiki makes you go back to the bottom of the circle around the tree, and a reset trigger could be used there at least.

![buffixrhuber2](https://f.cloud.github.com/assets/7010874/2500405/533bc0e2-b362-11e3-8f3f-93d060bee5a1.jpg)

**Comment by rhuberga** [comment]
Intentionally designed this way. Do you still think it should be changed? Eric, care to weigh in?
