### ISSUE TITLE
Waterfall Escape

### ISSUE THREAD

**Issue by esmith2** [RinglingGameArt/2014-Racing-Game#239]
@kreichwe by angling left on the waterfall jump you can escape the level

![screenshot00008](https://f.cloud.github.com/assets/7010873/2500464/f21ff188-b362-11e3-9f68-dc33fd252ae5.png)

**Comment by egingric** [comment]
Who's level is this? Please assign it to that person.

**Comment by kreichwe** [comment]
Area now obstructed by a boulder.
