### ISSUE TITLE
Sharp Unfinished Polygonal Edges

### ISSUE THREAD

**Issue by egingric** [RinglingGameArt/2014-Racing-Game#240]
These obviously inorganic and are apparent throughout level. Set Dress. Vary edges. Please improve them.
![sharp](https://f.cloud.github.com/assets/3945065/2500462/f172de76-b362-11e3-9091-e6bcc5f117de.jpg)

**Comment by rhuberga** [comment]
Every edge in this particular screenshot has been resolved.
Edges of track are all that remain to fix.
