### ISSUE TITLE
Fence on the Bank

### ISSUE THREAD

**Issue by AJSHanson** [RinglingGameArt/2014-Racing-Game#244]
Banked turn inside the cave needs some fences.
![kr_02](https://f.cloud.github.com/assets/3964555/2500508/59929028-b363-11e3-82a1-766fd7800f47.jpg)

**Comment by AJSHanson** [comment]
The cave wall doesn't have collision so you'll fly off the map if you exit the track on the banked turn- this should be fine one fences/ borders are added though since you won't be able to get there.

**Comment by kreichwe** [comment]
added barriers
