### ISSUE TITLE
Startline Flipper Strangeness

### ISSUE THREAD

**Issue by sreynold** [RinglingGameArt/2014-Racing-Game#253]
The flippers at your player start are kind of strange. I feel like I shouldn't be able to go through them, it doesn't really look right. if they're static you should probably move them out of the way so players can go through the middle passageway between them but not THROUGH the mesh.

**Comment by cbernosk** [comment]
I've put collision on the flippers. You shouldn't be able to go through them now. If you do somehow though just throw me another issue/message!!
