### ISSUE TITLE
Track smoothness

### ISSUE THREAD

**Issue by sreynold** [RinglingGameArt/2014-Racing-Game#261]
You have a lot of areas where the track comes up really abruptly. it's easy to run into these spots or see down through the track. Maybe you should try making a piece that goes horizontally along these seams to kind of cover them up and make it easier to drive on. 

![screenshot00000](https://f.cloud.github.com/assets/7013408/2502259/54cac1a2-b375-11e3-843b-8f831cb19630.jpg)

**Comment by cbernosk** [comment]
Although still a little bumpy in some areas, the newer track has fixed the issues that you've pointed out!
