### ISSUE TITLE
Gap in track before first robot jump

### ISSUE THREAD

**Issue by dcollins2** [RinglingGameArt/2014-Racing-Game#262]
At the bottom of the ramp for the first robot jump, there is a gap in the track that cars can run into. 
![screenshot00000](https://f.cloud.github.com/assets/7013425/2502270/79f66224-b375-11e3-982f-7e0b1bd2416e.jpg)

**Comment by cbernosk** [comment]
The gap is gone thanks to the newer version of the track. Also, sorry I didn't send this comment to you sooner!
