### ISSUE TITLE
No trigger for path nodes: Falling forever

### ISSUE THREAD

**Issue by sreynold** [RinglingGameArt/2014-Racing-Game#269]
So right at this jump, I fell a couple of times and much of the time there was no trigger to catch my fall. Make sure you have triggers covering this whole area as it's a "high fall" zone.

![screenshot00001](https://f.cloud.github.com/assets/7013408/2502319/f8bcbff4-b375-11e3-84bf-62bb4196f201.jpg)

**Comment by cbernosk** [comment]
Fixed with the newer version.Should be able to hit the trigger now if you fall from this point on the newer track.
