### ISSUE TITLE
respawn point/path node facing the wrong direction 

### ISSUE THREAD

**Issue by mcassin** [RinglingGameArt/2014-Racing-Game#270]
the respawn point by the flashing blue arrows about halfway through the level points you towards the arrows rather than the correct way down the track
![screenshot00000](https://f.cloud.github.com/assets/7049540/2502335/1b836eac-b376-11e3-9120-e8e75f4219b9.jpg)

**Comment by egingric** [comment]
Who's level is this? Please assign it to that person.
