### ISSUE TITLE
Lo-Rez Rock Texture W/ Seams

### ISSUE THREAD

**Issue by egingric** [RinglingGameArt/2014-Racing-Game#280]
Texture tiling is too low if we can get this close to it.
![lo-resnseams](https://f.cloud.github.com/assets/3945065/2502370/b5df64c4-b376-11e3-85a8-b3aef3a64587.jpg)

**Comment by sreynold** [comment]
I reuved my mesh so it shouldn't be a problem in someone else's level now.
