### ISSUE TITLE
Lightbulb Radius

### ISSUE THREAD

**Issue by sreynold** [RinglingGameArt/2014-Racing-Game#285]
I feel like the radius for the trigger in which the lightbulbs launch you into the air is too high. I've been launched when I'm really not very close to them at all. Also, throughout your level I feel I'm constantly being tossed into the air, it makes things really disorienting and kind of annoying and unfun to play. When I'm launched in the air, every time I have to reconfigure where I am in your map (In which I already find kind of hard to tell where and in what direction I'm going).

**Comment by dcollins2** [comment]
Lowered radius on lightbulb bumpers. Hopefully that helps make it less disorienting.

**Comment by dcollins2** [comment]
The radius and strength of the bumpers are now much lower.
