### ISSUE TITLE
Collision Issue with Bumpers and Cavern Wall

### ISSUE THREAD

**Issue by jwhamer** [RinglingGameArt/2014-Racing-Game#286]
Getting bumped by the bumper force actor into the wall will result in a collision error where you cannot move.

![screenshot00000](https://f.cloud.github.com/assets/7049541/2502399/0e7d05fa-b377-11e3-8af6-7ff72b3e82a5.jpg)

**Comment by tzdancew** [comment]
I fixed this. you no longer get stuck in the rock.
