### ISSUE TITLE
bumper pushing car into rocks

### ISSUE THREAD

**Issue by mcassin** [RinglingGameArt/2014-Racing-Game#296]
When hitting the first bumper in the bumper zone the bumper flung me through the rock and my car got stuck. maybe try moving the bumper away from the wall

![screenshot00000 copy](https://f.cloud.github.com/assets/7049540/2502433/814cfa9a-b377-11e3-8902-b32af2593ab9.jpg)

**Comment by tzdancew** [comment]
Fixed the rock collision so you don't get stuck there. I also moved the first bumper
