### ISSUE TITLE
Crystal Meteor Does Not Move Realistically

### ISSUE THREAD

**Issue by egingric** [RinglingGameArt/2014-Racing-Game#299]
Should not ease out at the end. Should have an impact effect. Should shatter when I hit it, or do something interesting.
![cystalboo](https://f.cloud.github.com/assets/3945065/2502457/c7e0737e-b377-11e3-8341-773e961cfe3f.jpg)

**Comment by tzdancew** [comment]
added impact effect and doesn't ease in and out when moves. It doesn't shatter when it gets hit
