### ISSUE TITLE
Dragon's Mouth does not stop me

### ISSUE THREAD

**Issue by jwhamer** [RinglingGameArt/2014-Racing-Game#303]
I feel like it should be more of an obstacle, but even at its lowest it's not stopping me from entering the cave. Was this on purpose?

**Comment by tzdancew** [comment]
I'm aware of this. The plan is to make it like the spiky trap we did in programming class. I was having trouble getting the kill trigger to attach to the base of the dragons head after i added the new head so  i left it alone for alpha. Before beta It will work just as the spiky trap worked.

**Comment by tzdancew** [comment]
took out dragon's head. this problem no longer matters
