### ISSUE TITLE
Can't See Dragon Head Well

### ISSUE THREAD

**Issue by egingric** [RinglingGameArt/2014-Racing-Game#307]
Need a side view of the dragon head as we approach it so we can see it in all it's gloy. Currently does not read and is underwhelming from the front.
![whatisit](https://f.cloud.github.com/assets/3945065/2502488/28b873f4-b378-11e3-987f-b91c36139507.jpg)

**Comment by tzdancew** [comment]
took dragon out completely. Couldn't find a way to show it off without major reworking of my map. The dragon was giving me too many problems overall so i decided to get ride of it all together.
