### ISSUE TITLE
difficult to know what direction to go

### ISSUE THREAD

**Issue by mcassin** [RinglingGameArt/2014-Racing-Game#316]
it's difficult to determine which was to go in this area, maybe consider adding arrows on the walls or lighting it up alittle

![screenshot00000 copy](https://f.cloud.github.com/assets/7049540/2502563/062f4b72-b379-11e3-9c6e-ca06ace23233.jpg)

**Comment by athomas1** [comment]
I added arrows along the wall which make it clearer which direction you're going.
