### ISSUE TITLE
stuck between the flipper and the railing

### ISSUE THREAD

**Issue by mcassin** [RinglingGameArt/2014-Racing-Game#321]
you get stuck between the the railing and the bumpers and are unable to move out or boost out

![screenshot00000](https://f.cloud.github.com/assets/7049540/2502601/5e0540ea-b379-11e3-93fc-0f95ddf53070.jpg)

**Comment by athomas1** [comment]
I added an extra piece of rail there. I tried getting stuck there, but every time I was able to get out.
