### ISSUE TITLE
Not enough detail / set dressing / layers

### ISSUE THREAD

**Issue by egingric** [RinglingGameArt/2014-Racing-Game#330]
Can't just have a giant wall on the edge of the play space with an obvious repeating texture on it. Fill it with layers of backg
![giantblankness](https://f.cloud.github.com/assets/3945065/2502634/c17ba22c-b379-11e3-95a7-b28be850cba8.jpg)
round set dressing.

**Comment by athomas1** [comment]
added planets along walls
