### ISSUE TITLE
Collision on shortcut not working

### ISSUE THREAD

**Issue by jwhamer** [RinglingGameArt/2014-Racing-Game#333]
The SUPER shortcut doesn't have collision, so I can't drive on it.
![screenshot00003](https://f.cloud.github.com/assets/7049541/2502646/d7088416-b379-11e3-9265-e90c538021de.jpg)

**Comment by athomas1** [comment]
Jose's model. Can you add collision to the glass as well?

**Comment by jmmendoza** [comment]
Added
