### ISSUE TITLE
Camera not facing car during countdown

### ISSUE THREAD

**Issue by dcollins2** [RinglingGameArt/2014-Racing-Game#335]
The camera faces the wall instead of the back of the car during the initial countdown.

**Comment by sreynold** [comment]
I do not have control over this issue. Eric and I discussed in class that this was something he needed to fix so I'm forwarding it to him.

**Comment by egingric** [comment]
Actually I now realize you will want to rotate you target point towards your car to fix this. I will be flying the camera from the target point to the car at some point.

**Comment by sreynold** [comment]
Turned target point. Fixed.
