### ISSUE TITLE
Lighting issue on rock model

### ISSUE THREAD

**Issue by dcollins2** [RinglingGameArt/2014-Racing-Game#339]
There is a lighting issue on the rocks shown in this screenshot.
![screenshot00003](https://f.cloud.github.com/assets/7013425/2502731/f03bbb1e-b37a-11e3-920c-67fd40a57258.jpg)

**Comment by sreynold** [comment]
That specific model decided it didn't want to light for no reason I can tell so I just removed it from the world and replaced it.
