### ISSUE TITLE
Rocks Too Low-Rez n Seamy

### ISSUE THREAD

**Issue by egingric** [RinglingGameArt/2014-Racing-Game#342]
Rocks need more poly's, less blurry textures if we can get this close, and they seem to have seams.
![toolow-rez](https://f.cloud.github.com/assets/3945065/2502767/4dc51708-b37b-11e3-8458-d1557d3d4e1d.jpg)

**Comment by jwhamer** [comment]
Redid textures on rocks, should hopefully look less low-poly and seam-y (also used fire particle effects to cover seams...)
