### ISSUE TITLE
The camera is showing the wall and not the back of the car

### ISSUE THREAD

**Issue by jmmendoza** [RinglingGameArt/2014-Racing-Game#353]
![dddddd](https://f.cloud.github.com/assets/7013427/2502837/cc10eac4-b37b-11e3-865b-7807ffd9ec21.jpg)

**Comment by sreynold** [comment]
Dylan submitted the same issue. I already sent that one to Eric, this is out of my control it's an issue on Eric's end so I'm closing this.
