### ISSUE TITLE
Track hill near end of level seems a tad high.

### ISSUE THREAD

**Issue by cbernosk** [RinglingGameArt/2014-Racing-Game#354]
The incline the player drives up before they make it to the finish line is a bit too high so the player just drags along up it. Consider putting a boostpad maybe?
![si1](https://f.cloud.github.com/assets/7013406/2502846/dc189be2-b37b-11e3-83ce-610b2a499e8a.jpg)

**Comment by sreynold** [comment]
Added boost pads to inclines.
