### ISSUE TITLE
Car gets stuck in flipper

### ISSUE THREAD

**Issue by dcollins2** [RinglingGameArt/2014-Racing-Game#360]
The car can get stuck in the red and white pinball flippers when approached from certain angles.
![screenshot00007](https://f.cloud.github.com/assets/7013425/2502927/c79ac842-b37c-11e3-9aa6-6bb3ce10e547.jpg)

**Comment by slee3** [comment]
that was my collision issue, so I remade the collision of it. Now the vehicle will not get stuck with it. Thanks!
