### ISSUE TITLE
Rails

### ISSUE THREAD

**Issue by athomas1** [RinglingGameArt/2014-Racing-Game#361]
Some parts of your level don't have rails which caused me to fall off the track.

**Comment by jwhamer** [comment]
Where in the level are there not rails? in some cases it is intentional

**Comment by athomas1** [comment]
![rails](https://f.cloud.github.com/assets/7013400/2503487/c9603a76-b382-11e3-822c-84cba365916c.jpg)

**Comment by jwhamer** [comment]
added rails to all necessary places~
