### ISSUE TITLE
Level Break Issue

### ISSUE THREAD

**Issue by cbernosk** [RinglingGameArt/2014-Racing-Game#369]
The very first part of your level knocked me right out of the level! Maybe you should find some way to put collision up near the areas where players can break out of the level.

![sl1](https://f.cloud.github.com/assets/7013406/2502964/3f5fb5d6-b37d-11e3-95c8-9bf5a9673176.jpg)

**Comment by slee3** [comment]
I see the some of part dose not have fence, so I blocked all and check the collision. Thanks!
