### ISSUE TITLE
Walls are invisible until collision

### ISSUE THREAD

**Issue by dcollins2** [RinglingGameArt/2014-Racing-Game#370]
The walls in one section of the track don't appear until they are hit by the car. When they do appear, they seem to have lighting issues. Here is a screenshot of the area with one of the walls that appeared after I collided with it.
![screenshot00008](https://f.cloud.github.com/assets/7013425/2502974/456382a0-b37d-11e3-9d8f-43b14caa6d30.jpg)

**Comment by slee3** [comment]
I am not sure about this problem because usually they work.... but sometimes they disappear like the screenshot... maybe the apex problem? I am not sure. 
about the lighting problem, I checked dynamic shadow options...

**Comment by slee3** [comment]
I replaced the APEX walls!
