### ISSUE TITLE
Scale Too Big on many assets

### ISSUE THREAD

**Issue by egingric** [RinglingGameArt/2014-Racing-Game#373]
This is way too big. Needs to be much closer to real life. Many other assets in you level suffer from this as well.
![scaletoobig](https://f.cloud.github.com/assets/3945065/2502984/65a3d916-b37d-11e3-9fe5-e01d599ab59d.jpg)

**Comment by mcassin** [comment]
entire level was scaled down so that more assets and vistas are in view
