### ISSUE TITLE
Too Many Flippers?!

### ISSUE THREAD

**Issue by cbernosk** [RinglingGameArt/2014-Racing-Game#376]
It’s a tad challenging to get through the very first part of your track due to all the flippers going off. You may want to either slow them down or get rid of some so the player isn’t stuck getting flipped around before they can even get to the rest of the race.

![sl3](https://f.cloud.github.com/assets/7013406/2502994/8b3175f8-b37d-11e3-9186-ce8128ed4a04.jpg)

**Comment by slee3** [comment]
yes... I reduced the number of traps and changed the timing and angle. Now they block the vehicle but not throw out the vehicle to the outside. and I also resized the reset tirggers..just in case.
