### ISSUE TITLE
Can't make this jump

### ISSUE THREAD

**Issue by sreynold** [RinglingGameArt/2014-Racing-Game#380]
I can't make this jump. I don't think that's because I'm bad, I think that's because it's a bit too high. 
![screenshot00007](https://f.cloud.github.com/assets/7013408/2503022/be3b0e32-b37d-11e3-8a71-b49d7e945c02.jpg)

**Comment by slee3** [comment]
yeap, that was not your fault.. I also tried several times but it was hard to make without the boost,, 
I changed the height of slope and for me, It works now. Thanks!
