### ISSUE TITLE
Stuck

### ISSUE THREAD

**Issue by Kjohnso1** [RinglingGameArt/2014-Racing-Game#387]
![mikebug](https://f.cloud.github.com/assets/7014979/2504570/fcffe000-b38e-11e3-97b9-1c4d97b9d260.jpg)
I think this is meant to be a jump, but I didn't boost and I'm now stuck between the ramp and the section of track which I should have landed on. There is no way to get out of this hole. 

Edit: I repeated this jump a few more times, and you can jump without a boost, but only if you have enough speed, which I did not a few times. Easy fix as long as you remove the gap.

**Comment by mmarra228** [comment]
The gap has been removed.

**Comment by mmarra228** [comment]
Fixed.
