### ISSUE TITLE
Checkpoint in spinning tunnel

### ISSUE THREAD

**Issue by mvarde** [RinglingGameArt/2014-Racing-Game#390]
If you fall off the track right before the rotating tunnel: maybe the checkpoint should be before the tunnel, not IN the tunnel because you start rolling around immediately when you re-spawn and its kind of confusing.
![screenshot00000](https://f.cloud.github.com/assets/7014943/2504551/c67b5258-b38e-11e3-845a-54c493cfb008.jpg)

**Comment by bshively** [comment]
Moved checkpoint back before the jump.
