### ISSUE TITLE
Off the track

### ISSUE THREAD

**Issue by Kjohnso1** [RinglingGameArt/2014-Racing-Game#395]
![andybug](https://f.cloud.github.com/assets/7014979/2504664/2ed45402-b390-11e3-83ac-c3d955b5e8ae.jpg)
![andybug2](https://f.cloud.github.com/assets/7014979/2504692/a1e03ace-b390-11e3-81fc-390b603ae0e5.jpg)

It's possible to drive around outside your track and not die.

**Comment by langandy** [comment]
Added reset triggers.
