### ISSUE TITLE
I got my Jimmy lodged in Mike's crevasse.

### ISSUE THREAD

**Issue by langandy** [RinglingGameArt/2014-Racing-Game#396]
There's a gap along the inner wall of one of your turns. I got my car stuck in it. You might want to consult a doctor.
![screenshot00003](https://f.cloud.github.com/assets/7014959/2504646/10c8240c-b390-11e3-89e8-91da73a4d7f3.jpg)

**Comment by mmarra228** [comment]
Added a floor piece underneath so now its impossible to get stuck there.

**Comment by mmarra228** [comment]
Fixed.
