### ISSUE TITLE
Reset to checkpoint when approaching wall on side of track

### ISSUE THREAD

**Issue by dcollins2** [RinglingGameArt/2014-Racing-Game#40]
When I drive towards the wall to the left of the section immediately after the bridge jump the car resets to the checkpoint. I circled the wall in this screenshot:

![trackbug3](https://f.cloud.github.com/assets/7013425/2475967/7baae5a6-b05d-11e3-81ba-5f0cb065c596.jpg)

**Comment by mcassin** [comment]
I moved the trigger so that won't happen anymore.
