### ISSUE TITLE
Dark

### ISSUE THREAD

**Issue by bshively** [RinglingGameArt/2014-Racing-Game#405]
When the lights flicker in this area it gets pitch black and make it a little hard to see. Try having this set of lights flicker more like your other ones. That way they don't get so dark.
![screenshot00002](https://f.cloud.github.com/assets/7014940/2504738/f8c32dd8-b390-11e3-9764-d4806df8e4b2.jpg)

**Comment by mvarde** [comment]
I added a secondary light that always stays on so it isn't so dark when the other lights flicker.
