### ISSUE TITLE
Launched Out of the World !

### ISSUE THREAD

**Issue by rlonchar** [RinglingGameArt/2014-Racing-Game#421]
![launchedoutoftheworld](https://f.cloud.github.com/assets/7013553/2504870/cfd58946-b392-11e3-82ac-48171f4136f9.jpg)

When I hit your obstacles that are moving up and down, I was in mid boost and it launched me off of the track and out into the abyss. I must have cleared one of your checkpoints.

**Comment by egingric** [comment]
Who's level is this? Please assign it to that person.
