### ISSUE TITLE
Fell into the infinite abyss.

### ISSUE THREAD

**Issue by langandy** [RinglingGameArt/2014-Racing-Game#425]
I fell off the track, but I kept falling and didn't get reset to a check point.  I'm not sure where it was exactly because I drove off the track and went to the bathroom.  When I came back, I was still falling.
![screenshot00004](https://f.cloud.github.com/assets/7014959/2504890/376abc70-b393-11e3-8875-50af761b5c61.jpg)

**Comment by Kjohnso1** [comment]
Expanded trigger
