### ISSUE TITLE
No Kill

### ISSUE THREAD

**Issue by screeley013** [RinglingGameArt/2014-Racing-Game#426]
![screenshot00012](https://f.cloud.github.com/assets/7014972/2504889/2bb66dac-b393-11e3-909c-24858659f9ae.jpg)

Around the beginning of the level, where is no kill z and you fall into darkness

**Comment by egingric** [comment]
Who's level is this? Please assign it to that person.

**Comment by cpavlovs** [comment]
Fixed by hyper-extending the trigger
