### ISSUE TITLE
Landed in a weird place

### ISSUE THREAD

**Issue by mvarde** [RinglingGameArt/2014-Racing-Game#431]
If you fall off the track at the first decline, you can land on the floor below and drive around. Its not very fun to have to drive around and find a checkpoint, just move the trigger up a little bit above that floor. Or give that track some railings.
![screenshot00006](https://f.cloud.github.com/assets/7014943/2504972/380d510a-b394-11e3-96f4-ea023a1d8a98.jpg)

**Comment by screeley013** [comment]
Fixed It!
