### ISSUE TITLE
Shot through the roof

### ISSUE THREAD

**Issue by bshively** [RinglingGameArt/2014-Racing-Game#440]
If the car is on top of one of your robots, and the the robot launches up, the car gets shot right through your roof lol Maybe have some sort of collision (even a simple blocking volume) on the roof so the player just falls back down and doesn't go out of the world.
![screenshot00007](https://f.cloud.github.com/assets/7014940/2505025/f9c0b6a2-b394-11e3-9dd2-e338aabdb62a.jpg)

**Comment by screeley013** [comment]
Fixed It!
