### ISSUE TITLE
Barriers

### ISSUE THREAD

**Issue by Kjohnso1** [RinglingGameArt/2014-Racing-Game#445]
![katbug2](https://f.cloud.github.com/assets/7014979/2505097/fe9ff772-b395-11e3-9d19-5bf447e070fb.jpg)
![katbug](https://f.cloud.github.com/assets/7014979/2505098/fea03142-b395-11e3-8de3-b564927bf9d5.jpg)

There are a few different spots that I can get out of the main track area and ride around in places I shouldn't be. Add some barriers to stop this, or triggers so it will reset the player.

**Comment by kcollins12** [comment]
Added railings to everything.
