### ISSUE TITLE
Small Opening in Wall

### ISSUE THREAD

**Issue by mmarra228** [RinglingGameArt/2014-Racing-Game#451]
In the part of your track with the moving dice, there is a small opening in the wall which allows the player to drive outside of the boundaries of your track. If you look at the first image, I have highlighted with a red square, the area in which the player can break the boundaries.

![kat](https://f.cloud.github.com/assets/7014945/2505107/1ea2b32a-b396-11e3-92d9-c614716fed2b.jpg)

**Comment by kcollins12** [comment]
fixed
