### ISSUE TITLE
I died

### ISSUE THREAD

**Issue by bshively** [RinglingGameArt/2014-Racing-Game#455]
I got hit with one of the blue bouncy balls / light bulbs, and it blew up my car instantly and ended the game for me.
![screenshot00016](https://f.cloud.github.com/assets/7014940/2505212/1542dad4-b397-11e3-89d1-167e0ae73a19.jpg)

**Comment by egallaha** [comment]
Unfortunately this is intentional, the blue balls are very easy to avoid + have markers. I wish it wouldn't end the game for people, but that's part of the original kismet programming.
