### ISSUE TITLE
Driving under track.

### ISSUE THREAD

**Issue by langandy** [RinglingGameArt/2014-Racing-Game#459]
If I go off to the side of the jump where you're supposed to crash through the glass, I can ignore the collision on your ground and get under the track.
![screenshot00005](https://f.cloud.github.com/assets/7014959/2505245/5f1dd47e-b397-11e3-8095-1b9f3a5c9e96.jpg)

**Comment by egallaha** [comment]
Trigger wasn't attached in kismet for whatever reason. Fixed!
