### ISSUE TITLE
Floating tree

### ISSUE THREAD

**Issue by mvarde** [RinglingGameArt/2014-Racing-Game#463]
There is a very precariously perched tree over here somewhere (sorry idk where I am) and I am worried for it.
![screenshot00007](https://f.cloud.github.com/assets/7014943/2505298/e0ec6812-b397-11e3-899e-0aaaa16efcfc.jpg)

**Comment by egallaha** [comment]
I am sorry to cause you worry. I have talked to this tree and they have decided to position themselves correctly. Thank you for your concern.
