### ISSUE TITLE
Sharp edges, repeating textures.

### ISSUE THREAD

**Issue by egingric** [RinglingGameArt/2014-Racing-Game#470]
This happens throughout your level on all of your track assets. Need to roughen, hide your edges behind set dressing and blend your textures near the edges on order to make all your assets look more natural and less digital.
![sharp](https://f.cloud.github.com/assets/3945065/2515371/f086cb5e-b442-11e3-88a9-2d2d528d93f8.jpg)

**Comment by bakedpudding** [comment]
Fixed the temple Edges, added a better texture to the cliff walls
