### ISSUE TITLE
Car

### ISSUE THREAD

**Issue by bakedpudding** [RinglingGameArt/2014-Racing-Game#483]
Car opens in car select, but can not play it in a level.

**Comment by egingric** [comment]
Works for me in the level, but it looks kinda funny. Please fix!
![squished](https://cloud.githubusercontent.com/assets/3945065/2542162/2b18027c-b5e4-11e3-9d0e-4277f3f26bf1.jpg)

**Comment by bakedpudding** [comment]
I have gotten the car to work, and not it is looking better than ever.
