### ISSUE TITLE
No Vehicle Factory Exists

### ISSUE THREAD

**Issue by egingric** [RinglingGameArt/2014-Racing-Game#486]
Trying to spawn your vehicle in the vehicle select map, but it appears you have no vehicle factory anymore. Please recreate your vehicle factory, ASAP.

@scarrollrcad FYI.

**Comment by wpaulsen** [comment]
Factory Added.

**Comment by egingric** [comment]
I can't find it in the actor list. If it exists it doesn't seem to start with wpaulsen. Can you direct me to what it is called ASAP?

**Comment by egingric** [comment]
Please assign the bug TO ME when you think you have fixed it or have info for me. This makes it MUCH easier for me to find it again.

**Comment by wpaulsen** [comment]
This was added back in a while ago. My apologies for the late bug close.
