### ISSUE TITLE
No Vehicle Factory To Be Found

### ISSUE THREAD

**Issue by egingric** [RinglingGameArt/2014-Racing-Game#487]
Trying to spawn your vehicle in the vehicle select map, but it appears you have no vehicle factory anymore. Please recreate your vehicle factory, ASAP.

@scarrollrcad FYI.

**Comment by sreynold** [comment]
I went through the vehicle import process, however, UDK crashes when I place my vehicle into the world so I have no way to test it. I know other people are receiving the same error.

**Comment by egingric** [comment]
Hopefully your re-weighting will fix this. Assign bug back to me when it works.

**Comment by egingric** [comment]
It worked... now it crashes. I had to remove it from the vehicle select screen.

**Comment by sreynold** [comment]
I haven't touched it since we fixed it yesterday and I submitted all of the changes etc. So, I'm not really sure how to troubleshoot  that.
