### ISSUE TITLE
Vehicle Factory Gone Missing

### ISSUE THREAD

**Issue by egingric** [RinglingGameArt/2014-Racing-Game#488]
Trying to spawn your vehicle in the vehicle select map, but it appears you have no vehicle factory anymore. Please recreate your vehicle factory, ASAP.

@scarrollrcad FYI.

**Comment by egingric** [comment]
Hey, we need this to work, now. Please get on this immediately, or tell me you will not be fixing it, and I will go ahead and cut it from the game.

**Comment by kcollins12** [comment]
Car is in the game.
