### ISSUE TITLE
Invisible Car

### ISSUE THREAD

**Issue by egingric** [RinglingGameArt/2014-Racing-Game#489]
When spawning your vehicle on the vehicle select screen nothing shows up. Please fix ASAP.

@scarrollrcad FYI.

**Comment by screeley013** [comment]
I'll make it a weekend project, thanks for the heads up !!

On Fri, Mar 28, 2014 at 11:01 AM, Eric D. Gingrich <notifications@github.com

**Comment by egingric** [comment]
Weekend is over and we need this to work now please. I will remove your vehicle from the game if this is not fixed soon.

**Comment by screeley013** [comment]
done
