### ISSUE TITLE
Car Spawning Fix

### ISSUE THREAD

**Issue by egingric** [RinglingGameArt/2014-Racing-Game#492]
Open the Kismet for your persistent map and delete the sequence indicated in the image below. 
![thiswillmessupcarandlevelchoice](https://cloud.githubusercontent.com/assets/3945065/2553370/800bf2be-b6a4-11e3-92dd-0c9672bbc8e7.jpg)

@rlonchar FYI.

**Comment by egallaha** [comment]
Fixed, thank you!
