### ISSUE TITLE
Fix for Car Spawning Error

### ISSUE THREAD

**Issue by egingric** [RinglingGameArt/2014-Racing-Game#493]
Open the Kismet for your persistent map and delete the sequence indicated in the image below. 
![thiswillmessupcarandlevelchoice](https://cloud.githubusercontent.com/assets/3945065/2553370/800bf2be-b6a4-11e3-92dd-0c9672bbc8e7.jpg)

@rlonchar FYI.

**Comment by rlonchar** [comment]
Is this referring to the issue Tudy and Hugo had? I was pretty sure I
didn't see that in Hugo's level when we were looking over his Kismet.

_Ryland Loncharich_
Ringling College of Art + Design
Computer Animation\* |\* Game Art and Design Faculty

**Comment by hgmares** [comment]
It didn't solved the problem, it seems like it loads the car but when the
race is supposed to start, it just brings the same error.

**Comment by egingric** [comment]
The outputs on the vehicle spawner are hooked up backwards.
![backwards](https://cloud.githubusercontent.com/assets/3945065/2568880/14b25838-b8e7-11e3-92c3-beaf0dad63c5.jpg)

**Comment by hgmares** [comment]
Hey Eric,

So in the car select menu if you press the right or left arrow keys many
times very fast the cars will start stocking on top each other, my personal
record is five : )

Regards,
Hugo

On Mon, Mar 31, 2014 at 11:14 AM, Eric D. Gingrich <notifications@github.com
