### ISSUE TITLE
Frame Rate and Stunt

### ISSUE THREAD

**Issue by bshively** [RinglingGameArt/2014-Racing-Game#52]
Frame rate dropped to 24 and 25 during your stunt. I also wasn't able to see your stunt happen. Maybe have it go off a little sooner so the player can see the items get sucked away, and then have a trigger to turn off the force actor so the car doesn't get sucked away.

**Comment by egingric** [comment]
Go thru your bugs Chris!!!!!

**Comment by cpavlovs** [comment]
SORRY I forgot about this one,
I ended up just removing a bunch of extra props and toning down the amount of glass on the destructible to fix this a while back.
