### ISSUE TITLE
Laps

### ISSUE THREAD

**Issue by esmith24601** [RinglingGameArt/2014-Racing-Game#530]
Path nodes are working but it takes 3 laps to complete track rather than 2.

(I don't know if this error has anything to do with it but thought I'd include it anyway)

![screenshot00000](https://cloud.githubusercontent.com/assets/7010906/2568273/6487e85c-b8e0-11e3-9777-d8056b744ee4.png)

@egingric

**Comment by egingric** [comment]
Race logic point 3 does not get hit on the fork to the right.

**Comment by esmith24601** [comment]
moved logic point 3 somewhere better, should work now
