### ISSUE TITLE
Vertex paint tool doesn't want to paint.

### ISSUE THREAD

**Issue by squinnspazdaxx** [RinglingGameArt/2014-Racing-Game#540]
@egingric 

Hey Ryland, I got the sub vertex system you showed us working correctly, but the vertex paint tool refuses to work when I move it off the main road texture. Like, the tool's icon just vanishes. Would you mind taking a look at it in class tomorrow?

**Comment by rlonchar** [comment]
Sure thing.

_Ryland Loncharich_
Ringling College of Art + Design
Computer Animation\* |\* Game Art and Design Faculty

**Comment by squinnspazdaxx** [comment]
Got it fixed! You we're right, reimporting the mesh did the trick!
