### ISSUE TITLE
Needle goes beyond speedometer max

### ISSUE THREAD

**Issue by mcassin** [RinglingGameArt/2014-Racing-Game#590]
![screenshot00001](https://cloud.githubusercontent.com/assets/7049540/2598443/ea171888-bac7-11e3-8761-f5fc210222ba.jpg)

**Comment by egingric** [comment]
Yeah, I FEVERISHLY fixed it before you were asked to copy the code but somehow you guys didn't get the message to SYNC / GET LATEST before copying the code. If you examine the needle math section in my map you will see the differences in the code.
