### ISSUE TITLE
MIC warning

### ISSUE THREAD

**Issue by rhuberga** [RinglingGameArt/2014-Racing-Game#602]
Game gives warnings for anyone using kismet to change parameters in material instance constants. Please hide this warning.
![untitled-1](https://cloud.githubusercontent.com/assets/7010882/2623578/97eef04c-bcf9-11e3-9faa-be6f46543b94.jpg)

**Comment by egingric** [comment]
Those will be hidden
 when we ship.

Regards,
-Eric

**Comment by egingric** [comment]
Hid.
