### ISSUE TITLE
Music Persists Across Levels: It Shouldn't.

### ISSUE THREAD

**Issue by egingric** [RinglingGameArt/2014-Racing-Game#608]
Flip this checkbox off and test to make sure you music does not persist when returning to the vehicle select screen.
![musicproblem](https://cloud.githubusercontent.com/assets/3945065/2637001/ec23cada-be97-11e3-895e-8195cf912248.jpg)

**Comment by egingric** [comment]
Hey, this is still happening. Very important to fix this ASAP.
@rlonchar Please check on this during game design class, if you don't mind.

**Comment by langandy** [comment]
Unchecked Persistent Across Levels on track node in Kismet.
