### ISSUE TITLE
Fix CanBoost Var in Main_Sequence

### ISSUE THREAD

**Issue by squinnspazdaxx** [RinglingGameArt/2014-Racing-Game#613]
The CanBoost Var in Main_Sequence that controls whether or not the "Boost!!" icon is grayed out or red is set to "True." This makes the "Boost!!" icon constantly stuck on red even after using a boost.

Please fix soon!

**Comment by egingric** [comment]
Did you change your mind?

**Comment by squinnspazdaxx** [comment]
I thought that was the problem, but now I'm not sure. See issues #614 and #615
