### ISSUE TITLE
Level doesn't end!

### ISSUE THREAD

**Issue by squinnspazdaxx** [RinglingGameArt/2014-Racing-Game#614]
@egingric 

Hey Eric, please help me! My level doesn't end and I don't know why!!

**Comment by squinnspazdaxx** [comment]
It does now! Kevin R helped me with 3 lap system so it's all good!

**Comment by egingric** [comment]
Switch it back to two laps please.

Regards,
-Eric

**Comment by squinnspazdaxx** [comment]
Done, and done!

On Thu, Apr 10, 2014 at 11:41 AM, Eric D. Gingrich <notifications@github.com
