### ISSUE TITLE
Lap 2 Not Working

### ISSUE THREAD

**Issue by bshively** [RinglingGameArt/2014-Racing-Game#620]
Race doesn't end after 2 laps. All pathnodes are hit.

**Comment by egingric** [comment]
Sterling's and Zach's aren't working either. Hmmm....

**Comment by bshively** [comment]
Hmm weird. I tried adding in that node from your persistence map to mine
and it didn't fix it.

**Comment by egingric** [comment]
Something else is going on. Grrrr...

Regards,
-Eric

**Comment by bshively** [comment]
I've been messing around with my level and realized the race does end, it's
just after 3 laps instead of two. I tried switching the node that I copied
from your persistence map from False to True, since it said "True for 2
laps, False for 3," but it didn't do anything. Hope this helps out some.

**Comment by egingric** [comment]
Thanks! Any other things you find out, keep 'em coming.

Regards,
-Eric

**Comment by egingric** [comment]
Fixed.
