### ISSUE TITLE
Mike Can't Be Bothered

### ISSUE THREAD

**Issue by egingric** [RinglingGameArt/2014-Racing-Game#628]
I will ask you to do this one last time. Please add this now. If you do not add this in the next 3 hours you will lose professionalism points off of your course average.

**Comment by mvolpa1** [comment]
I'm sorry I thought i did it already, I must've not uploaded to perforce.  I'll input it as soon as I get out of class.  A simple message saying the picture is not in game would have sufficed.

**Comment by egingric** [comment]
You just lost a professionalism point for disrespecting me.
