### ISSUE TITLE
Level Select Screen Tweaks

### ISSUE THREAD

**Issue by egingric** [RinglingGameArt/2014-Racing-Game#631]
Looks great! Except for two things...
1. You are getting some spawn vehicle warnings that I can't hide. Could be a case where another vehicle is blocking a spawn point where a new one is trying to spawn.
2. Please move the logo to the left, closer to the middle of the screen on a rule of third.
Thank you for your patience and dedication.

**Comment by dcollins2** [comment]
Adjusted spawn points to prevent spawn warnings and moved logo to the left.
