### ISSUE TITLE
Kismet Level Load Error 

### ISSUE THREAD

**Issue by dcollins2** [RinglingGameArt/2014-Racing-Game#634]
I get this error when I try to load my map: Kismet Warning:SeqAct_ActivateRemoteEvent UEDPCRACE-KismetMAP.TheWorld:PersistentLevel.Main_Sequence.SeqAct_ActivateRemoteEvent_9 failed to find target event: RaceSetUp
![loaderror](https://cloud.githubusercontent.com/assets/7013425/2663014/d908f1da-c04c-11e3-834a-cfaf6a21a56c.jpg)
When I go back to revision 70 for my map in perforce, I don't get this error, but all I changed in the newer versions was my HUD and some of my prefabs.

**Comment by egingric** [comment]
Does your map work despite the error?

Regards,
-Eric

**Comment by dcollins2** [comment]
No, the map stays in a black screen when played in PC mode.

**Comment by dcollins2** [comment]
I switched back to an older version and updated any changes that were lost and now the issue seems to be resolved.
