### ISSUE TITLE
Jumps

### ISSUE THREAD

**Issue by bshively** [RinglingGameArt/2014-Racing-Game#64]
The jumps are hard to land because the track is a little too offset. Even when I jump right off the center of the track I don't l
![screenshot00002](https://f.cloud.github.com/assets/7014940/2477555/6f9eab52-b072-11e3-9fcf-931287c85938.jpg)
and on the track.  The goats are awesome though!! :D

**Comment by egallaha** [comment]
Fixed! Hopefully!
