### ISSUE TITLE
Smart Car gets stuck in ground

### ISSUE THREAD

**Issue by dcollins2** [RinglingGameArt/2014-Racing-Game#645]
The smart car got stuck in the ground when I was playing your level.
![screenshot00010](https://cloud.githubusercontent.com/assets/7013425/2672198/a3124fbc-c0e3-11e3-94b8-e59cdf0f3593.jpg)
![screenshot00011](https://cloud.githubusercontent.com/assets/7013425/2672199/a31415ea-c0e3-11e3-8d4c-eaafcdf33327.jpg)

**Comment by athomas1** [comment]
I tried getting stuck here so many time. It hasn't happened to me once.
