### ISSUE TITLE
Mip Map issue for BOR

### ISSUE THREAD

**Issue by egingric** [RinglingGameArt/2014-Racing-Game#653]
THIS MORNING! Fix the mip-map issue (or whatever is wrong) with this prominent piece on your track for Best of Ringling. You have permission to check this in.

@rlonchar Ask Ryland for help if you can't figure this out.

**Comment by rlonchar** [comment]
Kevin, I am in 301 right now if you want to stop by and sync up here to sync up and look into this issue.

**Comment by kwhitmey** [comment]
gotcha ill get this done ASAP... i have rylands class in about 20 minutes

**Comment by egingric** [comment]
You need to get this in before 2PM.
