### ISSUE TITLE
One Rough Area Left

### ISSUE THREAD

**Issue by egingric** [RinglingGameArt/2014-Racing-Game#654]
You cave looks much better. So much better that I would like to put your level in for best of ringling. However there is still one rough area left where you have a giant obviously inserted chuck of geometry that is intersecting with previously set dressed objects and has a vast area of empty, unvaried, single texture repeat. No guarantee that I can get it in on time, but maybe if you update and check in your level before 2PM today.
![ug](https://cloud.githubusercontent.com/assets/3945065/2678497/c704c53e-c161-11e3-8d81-9d1a88c45fa6.jpg)

**Comment by kreichwe** [comment]
Thanks for the input and consideration. I've made changes to this area and
submitted it, working on rebuilding the lighting now. Let me know if there
is anything else I need to change!

**Comment by kreichwe** [comment]
Everything is polished up and submitted.
