### ISSUE TITLE
stray Collision

### ISSUE THREAD

**Issue by dpjergov** [RinglingGameArt/2014-Racing-Game#660]
I keep running into this invisible wall right after the main jump!!

![noooo](https://cloud.githubusercontent.com/assets/7013401/2680980/4a641b2a-c188-11e3-872c-875f53d3a949.jpg)

**Comment by dpjergov** [comment]
@egingric

**Comment by egingric** [comment]
@wpaulsen Please fix for E3.

**Comment by dpjergov** [comment]
Hey Eric, Sorry for the late reply- the internet here on campus has been a
little spotty as of late.

I wanted to ask if it was possible to hand in the re-submits of our levels
on Thursday rather than Monday, because of the restrictions placed on us
for E3 and Best of.

On Sun, Apr 13, 2014 at 10:45 AM, Eric D. Gingrich <notifications@github.com

**Comment by egingric** [comment]
Hmm, why? Just because you couldn't put your level in Perforce does not
mean you couldn't work on it.

Regards,
-Eric

**Comment by dpjergov** [comment]
Well the last time I tried to work on it without using perforce, all the
changes that I had made on it were deleted, even when I made a different
copy to try and make it writable.

If there is a way to work on it without perforce, than I apologize. I
didn't know. I guess I'll ask huber if he knows how to do that for future
reference. I'm sorry for bothering you.

**Comment by wpaulsen** [comment]
All fixed!

**Comment by egingric** [comment]
You aren't bothering me. Perforce is for backing up and sharing your work.
It doesn't delete your work. Talk to me during class and I can help you
with any questions you have.

Regards,
-Eric

**Comment by dpjergov** [comment]
Understood. See you in class then, and thanks.
