### ISSUE TITLE
Clipping issue?

### ISSUE THREAD

**Issue by jwhamer** [RinglingGameArt/2014-Racing-Game#664]
Rotating parts clip through exterior of spaceship
@egingric 

![untitled-4](https://cloud.githubusercontent.com/assets/7049541/2683221/4a8f4bdc-c1a7-11e3-9c48-9e95edeab06d.png)

**Comment by egingric** [comment]
Please fix for E3.

**Comment by rbaker7** [comment]
Gateway moved forward to avoid clipping! thank you, 
Ryan
