### ISSUE TITLE
Fall Out Of Level! 

### ISSUE THREAD

**Issue by cbernosk** [RinglingGameArt/2014-Racing-Game#666]
You can drive right off the track at the starting area to the right. I didn't hit a trigger so I was stuck and I was also able to completely drive through the mesh and drive through space!

![screenshot00000](https://cloud.githubusercontent.com/assets/7013406/2683280/d61881f0-c1a7-11e3-88e6-568cfa749f10.jpg)

![screenshot00001](https://cloud.githubusercontent.com/assets/7013406/2683281/d8d56b1a-c1a7-11e3-8d7e-447a22cef6d3.jpg)

**Comment by egingric** [comment]
@rbaker777 Please fix for E3.

**Comment by rbaker7** [comment]
Collision creating the mysterious invisible platform has been removed. thank you, 
ryan
