### ISSUE TITLE
Edge of skydome visible

### ISSUE THREAD

**Issue by jwhamer** [RinglingGameArt/2014-Racing-Game#669]
![untitled-6](https://cloud.githubusercontent.com/assets/7049541/2683435/620ef13e-c1a9-11e3-96ce-0889663f4d2c.png)
@egingric

**Comment by egingric** [comment]
Don't fix today!

**Comment by egingric** [comment]
Please fix for E3.

**Comment by kreichwe** [comment]
fixed
