### ISSUE TITLE
Mover Mesh Is Black!

### ISSUE THREAD

**Issue by cbernosk** [RinglingGameArt/2014-Racing-Game#674]
Your moving propeller near the starting line is completely black!!!!!

![screenshot00002](https://cloud.githubusercontent.com/assets/7013406/2683627/f61c8772-c1ab-11e3-9718-2a8b3c84d22b.jpg)

**Comment by egingric** [comment]
Please fix for E3.

**Comment by squinnspazdaxx** [comment]
Just checked both the propeller and turbine's normal facing direction in maya, reimported both into udk and re-attatched their materials. It's working now! Production level lighting build completed with update!
