### ISSUE TITLE
Clouds affected by normal maps

### ISSUE THREAD

**Issue by jwhamer** [RinglingGameArt/2014-Racing-Game#675]
![untitled-8](https://cloud.githubusercontent.com/assets/7049541/2683673/9f8abe1e-c1ac-11e3-9ce9-cae61847bfb7.png)
Eric says don't mind too much about fixing it, it won't be done by Best of, but it could be a nice thing to adjust later on. Maybe make a normal map for the clouds to occlude the normal map on the earth?

**Comment by dcollins2** [comment]
Added a mask for the clouds so they aren't affected by the normal map.
