### ISSUE TITLE
Hole in the wall

### ISSUE THREAD

**Issue by srussel1** [RinglingGameArt/2014-Racing-Game#676]
Found this hole in your level! Simple fix.

![screenshot00000](https://cloud.githubusercontent.com/assets/7010874/2683718/50e3a78e-c1ad-11e3-8db9-720124fe398a.jpg)

**Comment by egingric** [comment]
Please fix for E3.

**Comment by rbaker7** [comment]
Geometry fixed and the hole is repaired.
 Thank you,
Ryan
