### ISSUE TITLE
Fly out of world 

### ISSUE THREAD

**Issue by athomas1** [RinglingGameArt/2014-Racing-Game#678]
![screenshot00000](https://cloud.githubusercontent.com/assets/7013400/2684149/ff388fec-c1b3-11e3-9c34-3b1091274871.jpg)

If I boost right here I can fly out of your level.

**Comment by egingric** [comment]
Please fix for E3.

**Comment by dcollins2** [comment]
Added reset trigger behind the wall that can be jumped over.
