### ISSUE TITLE
I fall forever

### ISSUE THREAD

**Issue by mvolpa1** [RinglingGameArt/2014-Racing-Game#679]
I can fall forever in your world if I boost here.  When I try to respawn I dont.
![wtfmike](https://cloud.githubusercontent.com/assets/7010880/2684209/d6d6223e-c1b4-11e3-8f5f-2b0075b968e9.jpg)

**Comment by egingric** [comment]
@mmarra228 Please fix for E3.

**Comment by mmarra228** [comment]
Added a barricade so that players cannot get there.

**Comment by mmarra228** [comment]
Fixed.
