### ISSUE TITLE
Can't touch pathnode

### ISSUE THREAD

**Issue by wpaulsen** [RinglingGameArt/2014-Racing-Game#680]
Pathnode seems misplaced. It's up in the air and the player doesn't pass through it. Keeps me stuck on lap 1.

![here you go](https://cloud.githubusercontent.com/assets/7014941/2684278/cadbc924-c1b5-11e3-9fef-f9491ce8e8c6.jpg)

**Comment by egingric** [comment]
@rbaker777 Please fix if this has something do to with your laps not being counted.

**Comment by rbaker7** [comment]
Path node has been moved. and now works correctly. Thank you,
Ryan
