### ISSUE TITLE
APEX doors not working

### ISSUE THREAD

**Issue by mvarde** [RinglingGameArt/2014-Racing-Game#682]
@egingric My apex doors just pop into existence before you hit it for some reason and it looks really bad so I want to just replace it with movers that open with a trigger.

**Comment by egingric** [comment]
Are you asking me a question?

**Comment by mvarde** [comment]
I wasn't sure if we still had to ask for permission to check-in these types of changes so I just thought I'd let you know.

**Comment by egingric** [comment]
You don't. Go for it!

Regards,
-Eric

**Comment by egingric** [comment]
Just make sure you don't accidentally check in the Race-KismetMap!

Regards,
-Eric

**Comment by mvarde** [comment]
Replaced APEX doors with movers
