### ISSUE TITLE
Low car collision

### ISSUE THREAD

**Issue by rhuberga** [RinglingGameArt/2014-Racing-Game#699]
Just raised the collision on my car because it was catching on seams in Kwhitmey's level. Tried to play it with your car and it's catching too. Try raising it a bit.

**Comment by egingric** [comment]
This is ironic because I raised the collision on your car up a few days before that for the same reason. Dylan's car does need it's collision raised up but also...
@kwhitmey Kevin, you really have not addressed this very thoroughly in your level yet. Please take another pass on it.

**Comment by kwhitmey** [comment]
Got it. I'll take it to the next level Eric.
Thank you

**Comment by dcollins2** [comment]
Raised collision on smart car.
