### ISSUE TITLE
Can respawn out of level

### ISSUE THREAD

**Issue by mcassin** [RinglingGameArt/2014-Racing-Game#700]
When I press "E" for respawn while i'm on the piece of track the moves the car to the landing bay I can re spawn out of the tunnel piece into blank space.
![screenshot00000](https://cloud.githubusercontent.com/assets/7049540/2735459/3457226e-c660-11e3-9252-af7792d02010.jpg)

**Comment by bshively** [comment]
Relocated pathnode.
