### ISSUE TITLE
Can trigger rockslide before UFO does

### ISSUE THREAD

**Issue by jwhamer** [RinglingGameArt/2014-Racing-Game#701]
Running directly into the cliff face where the rockslide comes from on the first lap will cause some of the rocks to come unattached and fall to the course. Normally this would be cool, as it's diegetic and all, but one of the rocks literally catapulted me off the course. Due to a force actor, maybe? If the rocks were higher up on the cliff face I don't think this would be an issue.

**Comment by sreynold** [comment]
Checked out this issue
