### ISSUE TITLE
Vehicle Script Errors

### ISSUE THREAD

**Issue by egingric** [RinglingGameArt/2014-Racing-Game#703]
Looks like you either moved or deleted both your physics asset and your anim tree for your vehicle. It is very important to fix this now.

UTVehicle_CbernoskChevyImpala_Content.uc(13) : Warning, unresolved reference to 'AnimTree'cbernoskvehiclepkg.Anims.AT_CbernoskChevyImpala''

UTVehicle_CbernoskChevyImpala_Content.uc(14) : Warning, unresolved reference to 'PhysicsAsset'cbernoskvehiclepkg.Physics.SK_CbernoskChevyImpala_Physics''

@scarrollrcad Heads up.

**Comment by cbernosk** [comment]
Thanks for the heads up. I'll work on this asap after finishing up the
trailer!

-Caitlin

On Sun, Apr 27, 2014 at 10:43 AM, Eric D. Gingrich <notifications@github.com

**Comment by cbernosk** [comment]
Fixed! I adjusted the script accordingly and it's working fine now.
