### ISSUE TITLE
Last chance: Fix vehicle

### ISSUE THREAD

**Issue by egingric** [RinglingGameArt/2014-Racing-Game#709]
This is your last chance to fix your vehicle. Please fix it now.
![messedupjohnson](https://cloud.githubusercontent.com/assets/3945065/2812032/cad3ce5a-ce3e-11e3-89c5-889c427d102f.jpg)
@scarrollrcad Heads up.

**Comment by Kjohnso1** [comment]
This isn't my vehicle, and mine is working last time I looked at it.

**Comment by egingric** [comment]
My bad. Next time, open the bug right away when you first receive the email and assign it to the right person.
