### ISSUE TITLE
Sreynold Vehicle not spawning in Egallaha level

### ISSUE THREAD

**Issue by sreynold** [RinglingGameArt/2014-Racing-Game#722]
My car will not spawn in Tudy's level.

@egallaha

**Comment by egingric** [comment]
Assigning this to the proper person.

**Comment by egallaha** [comment]
This shouldn't be happening. Everything is right in my kismet code and my spawns are in the right place. Other cars spawn in fine.

**Comment by egingric** [comment]
Go into the actor factory's properties and make sure their vehicles are listed in there. Compare it to the other actor factories that are working. There is a drop down list of vehicles in the actor factory, so it should be relatively straightforward.

**Comment by egallaha** [comment]
Fixed
