### ISSUE TITLE
Car Floating

### ISSUE THREAD

**Issue by egingric** [RinglingGameArt/2014-Racing-Game#727]
Please fix it this morning!

**Comment by cbernosk** [comment]
Sorry, I haven't logged in until now and seen this! If I log into Perforce
and check out my vehicle package after I fix my car in Maya it shouldn't do
anything bad I hope?

-Caitlin

**Comment by cbernosk** [comment]
I deleted the extra joint and the car doesn't float anymore! I'll play it to see how it does in-game but seeing as it works fine in the editor it should be good now!

**Comment by egingric** [comment]
Nice job! Now please fix that giant brick of collision that pokes way
outside your vehicle mesh and goes down below your axles.

Regards,
-Eric
