### ISSUE TITLE
I can drive straight out of your level and do not respawn. I die instead.

### ISSUE THREAD

**Issue by squinnspazdaxx** [RinglingGameArt/2014-Racing-Game#731]
@egingric 

Dude, you seem to no have a reset trigger in your level.

Ya need a big-ass reset trigger below your entire level, yo!

Also, ya have no spawn points, add lots of 'em!

**Comment by cpavlovs** [comment]
I have both of these things and I can't find what you are talking about.
A picture showing me where this happened would be nice.

**Comment by squinnspazdaxx** [comment]
I just turned right at the start of your map and I fall 'till I die.

I just went off the first ramp in your level a bit too far to the left, missed the track, and fell 'till I died.

Ah, I see what'cha mean now. 2nd ramp is good!

**Comment by cpavlovs** [comment]
All my triggers are set up and I don't know why that is a problem. I made them all 50X bigger just in case.
