### ISSUE TITLE
Lap 2 broken on Hugo Gutierrez's map!

### ISSUE THREAD

**Issue by squinnspazdaxx** [RinglingGameArt/2014-Racing-Game#733]
@egingric @rlonchar 

I can't find Hugo Gutierrez on Git Hub, but his lap 2 never kicks in. Went around for four laps before I gave up.

**Comment by egingric** [comment]
Imprtant to fix this today!
@rlonchar

**Comment by hgmares** [comment]
looking into it right now

**Comment by hgmares** [comment]
didn't got any problem, raced it with several cars and couldn't reproduce the bug. could you specify the car you used

**Comment by hgmares** [comment]
Seems to be fine.I tested it with several cars through a shortcut without
the "editor".  No problem happen.
