### ISSUE TITLE
Update Your Car Reference List!

### ISSUE THREAD

**Issue by srussel1** [RinglingGameArt/2014-Racing-Game#744]
I noticed my car is popping up in your level as a Jimmy. You need to update the car spawner in your Kismet to change that. It's an easy fix.

@egingric 
![fixes4](https://cloud.githubusercontent.com/assets/7010874/2854068/1b20030a-d14c-11e3-8d6a-de7a30381499.jpg)

**Comment by egallaha** [comment]
I can't update it because udk crashes when I copy and paste it. I'll try copying just yours but no promises.
Won'tfix bug.

**Comment by egingric** [comment]
@rlonchar  Instead of copying and pasting, inside the vehicle spawner, go to the individual actor factory that has his name on it. Edit the properties, under the factory twirl down there is a list of vehicles. Choose his from the list. TEST before submitting.

**Comment by egallaha** [comment]
Oh yay! Fixed it for stephen's and other cars too.

**Comment by egingric** [comment]
Sweet! Did you test it?

Regards,
-Eric
