### ISSUE TITLE
Got Under Your Map!

### ISSUE THREAD

**Issue by srussel1** [RinglingGameArt/2014-Racing-Game#746]
I was being dragged by the side of the dice obstacles you have at the start of your race and somehow fell out of your map. Just put down some reset nodes, and it's all good!

![fixes6](https://cloud.githubusercontent.com/assets/7010874/2854468/4360a8ce-d151-11e3-863a-02637878debf.jpg)

**Comment by kcollins12** [comment]
weird. checked the spawn points and the triggers were working for me. Just in case, I added a path node.
