### ISSUE TITLE
Update Your Car Spawner In Kismet!

### ISSUE THREAD

**Issue by srussel1** [RinglingGameArt/2014-Racing-Game#748]
Your level spawns in an older version of the car spawner in Kismet. It had an error in it in which my car was swapped out for Scott Stevenson's car. just update the Car Spawner in your level's kismet and you're set.

@egingric 
![fixes7](https://cloud.githubusercontent.com/assets/7010874/2854650/7c01f0fa-d153-11e3-9834-e45c3550827c.jpg)

**Comment by egingric** [comment]
@rlonchar Important to fix this today!

**Comment by rbaker7** [comment]
upon checking the kismet, Steven's car was the only thing that needed updating. So this is now fixed, Hoooray!!!

**Comment by rbaker7** [comment]
fixed! thanks for the heads up!
