### ISSUE TITLE
Update Your Car Spawner In Kismet

### ISSUE THREAD

**Issue by srussel1** [RinglingGameArt/2014-Racing-Game#750]
My car's turning up as a white blockout because you have an outdated version of the Vehicle Spawner. Just get the updated version from Eric's Persistent map's Kismet and place it in yours.

@egingric 

![fixes8](https://cloud.githubusercontent.com/assets/7010874/2855820/7607b6cc-d161-11e3-9765-165174cbf06a.jpg)

**Comment by egingric** [comment]
Fix it Felix!

**Comment by rhuberga** [comment]
Oh, yeah sorry I did fix it earlier, I guess I never put that change on Perforce.
Fixed and tested.
