### ISSUE TITLE
Stunt

### ISSUE THREAD

**Issue by bshively** [RinglingGameArt/2014-Racing-Game#86]
I think your stunt is your big jump, so try making it even more epic by having like fighter jets or something flying through. Or maybe even have things shooting at the car like in star wars pod racers they have the desert characters who are shooting at the racers (sorry I forgot what the characters are called :P ) It would be awesome to jump and then have lasers shooting past you trying to shoot you down. :)

**Comment by egallaha** [comment]
This is an interesting suggestion but doesn't fit my theme very well. I will consider adding something else to make it more epic, though.

**Comment by bshively** [comment]
Whoops sorry that was for Mike Marra hahaha :)

**Comment by egallaha** [comment]
Oh whew! Haha, okay then. Reopened.

**Comment by mmarra228** [comment]
Too late to fix now.
