### ISSUE TITLE
90 degree turn

### ISSUE THREAD

**Issue by screeley013** [RinglingGameArt/2014-Racing-Game#87]
There was a path that was perpendicular to the rest of the track.... I zoomed by it the first time, and then took it the second (which took a while to line up and get into) I'm not sure if I was suppose to go there but I finished the track all the same. So just make it easier to get on to, or don't let me get onto it because I don't understand it's purpose...

**Comment by mmarra228** [comment]
I'm confused. Which turn are you talking about? The purpose it branches off is to offer different routes to the player for variety sake.

**Comment by mmarra228** [comment]
Not fixing.
